CREATE TABLE Person
(
  P_ID INT NOT NULL,
  Name VARCHAR(20) NOT NULL,
  Adress VARCHAR(20) NOT NULL,
  Phone VARCHAR(11) NOT NULL,
  Age INT NOT NULL,
  PRIMARY KEY (P_ID)
);

CREATE TABLE Doctor
(
  Rate VARCHAR(30) NOT NULL,
  Salery INT NOT NULL,
  P_ID INT NOT NULL,
  PRIMARY KEY (P_ID),
  FOREIGN KEY (P_ID) REFERENCES Person(P_ID)
);

CREATE TABLE Hospital
(
  Name VARCHAR(20) NOT NULL,
  Capacity INT NOT NULL,
  Adress VARCHAR(20) NOT NULL,
  H_ID INT NOT NULL,
  PRIMARY KEY (H_ID)
);

CREATE TABLE working_In
(
  Department VARCHAR(20) NOT NULL,
  P_ID INT NOT NULL,
  H_ID INT NOT NULL,
  PRIMARY KEY (P_ID, H_ID),
  FOREIGN KEY (P_ID) REFERENCES Doctor(P_ID),
  FOREIGN KEY (H_ID) REFERENCES Hospital(H_ID)
);

CREATE TABLE Sick
(
  Status INT NOT NULL,
  Department VARCHAR(20) NOT NULL,
  P_ID INT NOT NULL,
  H_ID INT NOT NULL,
  PRIMARY KEY (P_ID),
  FOREIGN KEY (P_ID) REFERENCES Person(P_ID),
  FOREIGN KEY (H_ID) REFERENCES Hospital(H_ID)
);
