CREATE TABLE Hotel
(
  ID NUMERIC(6) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Location VARCHAR(100) NOT NULL,
  Capacity NUMERIC(6) NOT NULL,
  Occupation NUMERIC(6) NOT NULL,
  PRIMARY KEY (ID)
);